# Generated by Django 3.1.14 on 2022-02-08 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0012_auto_20220208_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='articles', through='articles.UserArticleRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
