# Generated by Django 3.1.14 on 2022-02-09 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, upload_to='games/covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='subscribers',
            field=models.ManyToManyField(related_name='games', through='games.UserGameRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
