# Generated by Django 3.1.14 on 2022-02-08 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0010_auto_20220208_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarticlerelation',
            name='comment',
        ),
        migrations.AlterField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='articles', through='articles.UserArticleRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
